### PR TITLE
¡New Language Added!

### PR DESCRIPTION
**Pull request by ToastcodeDev**
I have integrated the **Spanish** language into the application, conducted thorough testing, and confirmed that it functions as anticipated. Please accept this contribution from me 😉.

- Toastcode

### CODE REVIEW

**Review by Lemkinator — CHANGES_REQUESTED** [review]
Thank you for your contribution! Unfortunately, you have also translated the strings of the libs. These are already translated in the libs (e.g. [here](https://github.com/OneUIProject/oneui-core/blob/sesl4/appcompat/src/main/res/values-es-rES/strings.xml)) and should not be included in the strings file of the app. The values-es/strings.xml file should only contain the strings from the [values/strings.xml](https://github.com/Lemkinator/Sudoku/blob/main/app/src/main/res/values/strings.xml) file, except the strings with translateable=false (just like the [values-de/strings.xml](https://github.com/Lemkinator/Sudoku/blob/main/app/src/main/res/values-de/strings.xml)). 

Additionally, it would be nice if the strings were in the same order as in the other strings.xml files.

**Comment by Lemkinator** [comment]
In order to make localization and per-app-language work for spanish 
an entry with name="es" needs to be added in [locale_config.xml](https://github.com/Lemkinator/Sudoku/blob/main/app/src/main/res/xml/locale_config.xml) 

```xml
<?xml version="1.0" encoding="utf-8"?>
<locale-config xmlns:android="http://schemas.android.com/apk/res/android">
    <locale android:name="en"/>
    <locale android:name="de"/>
    <locale android:name="es"/>
</locale-config>
```

and "es" and "es-rES" need to be added to [resourceConfigurations ](https://github.com/Lemkinator/Sudoku/blob/main/app/build.gradle.kts#L32)

```kts
resourceConfigurations += listOf("en", "de", "es", "es-rES")
```

**Comment by ToastcodeDev** [comment]
Implemented the improvements, although I did not add the ```
es-rES
``` value to the gradle module you could just copy the value and add the reference to the folder with that name.

**Review by ToastcodeDev — COMMENTED** [review]
Implemented the improvements, although I did not add the `es-rES` value to the gradle module you could just copy the value and add the reference to the folder with that name.

**Review by Lemkinator — APPROVED** [review]
Thank you for your contribution!
The es-rES value is necessary, even if there is no corresponding strings file in the app. The reason for that is, because the oneUI lib (where e.g. the sesl strings are translated) has some strings in this "es-rES" and not the normal "es" strings-file.

So if es-rES is not included, those strings default to english. 
But thats fine, i can change that once i have time. I also need to fix the setExtraText() in AboutActivity. Its crashing when spanish is selected, but thats because of my bad implementation :/ gonna fix that also later, before publishing to Google Play.

**Comment by Lemkinator** [comment]
tried to correct a few mistakes in [ee264a95442829d35ab0bb89ec87033727ede7f5](https://github.com/Lemkinator/Sudoku/commit/ee264a95442829d35ab0bb89ec87033727ede7f5), 
if i did something wrong, please let me know
if everything is fine, i will upload it to google play

**Comment by ToastcodeDev** [comment]
> Update is live👍🏽

It looks amazing in that language!

**Pull request merged**
